import type { Product, Category } from "./types"

export const mockCategories: Category[] = [
  { id: "1", slug: "sacs", name: "SACS", description: "Sacs à dos & Totes", image_url: null, position: 1 },
  { id: "2", slug: "accessories", name: "ACCESSOIRES", description: "Accessoires", image_url: null, position: 2 },
  { id: "3", slug: "new", name: "NOUVEAUTÉS", description: "Nouveautés", image_url: null, position: 3 },
]

const img = (id: string, w = 800, h = 1000) => `https://picsum.photos/seed/nayro-bag-${id}/${w}/${h}`

// Real NAYRO products based on Instagram nayro.shop (bags/backpacks)
export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "sac-a-dos-aola-kids-bleu",
    name: "Sac à dos AOLA KIDS",
    description: "Sac à dos AOLA KIDS — Style & Confort + Pratique. Compartiment principal spacieux, poches latérales, dos matelassé et bretelles réglables. Idéal pour l'école et les sorties. Matière résistante et légère.",
    short_description: "AOLA KIDS • 220 DH • Bleu/Jaune",
    price: 220,
    compare_at_price: null,
    sku: "NAY-SAC-AOLA-BLEU",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "1-1", product_id: "1", url: img("aola1"), alt: "Sac AOLA KIDS bleu", position: 0 },
      { id: "1-2", product_id: "1", url: img("aola2"), alt: "Sac AOLA KIDS détail", position: 1 },
    ],
    variants: [
      { id: "1-one", product_id: "1", size: "One Size", color_hex: "#0a0a0a", color: "Bleu/Jaune", sku: "NAY-SAC-AOLA-BLEU-OS", stock: 25, price_override: null, is_active: true },
    ],
  },
  {
    id: "2",
    slug: "sac-a-dos-gladly-noir",
    name: "Sac à dos Gladly Noir",
    description: "Sac à dos Gladly — design minimal et élégant, tissu déperlant, poche avant zippée, intérieur doublé. Parfait pour le quotidien et les déplacements. Porté par nos clientes à Casablanca.",
    short_description: "Gladly • Noir • Unisexe",
    price: 199,
    compare_at_price: 249,
    sku: "NAY-SAC-GLADLY-NOIR",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "2-1", product_id: "2", url: img("gladly1"), alt: "Sac Gladly noir", position: 0 },
      { id: "2-2", product_id: "2", url: img("gladly2"), alt: "Sac Gladly porté", position: 1 },
    ],
    variants: [
      { id: "2-one", product_id: "2", size: "One Size", color_hex: "#0a0a0a", color: "Noir", sku: "NAY-SAC-GLADLY-NOIR-OS", stock: 18, price_override: null, is_active: true },
    ],
  },
  {
    id: "3",
    slug: "tote-bag-canvas-trio",
    name: "Tote Bag Canvas Trio",
    description: "Lot de tote bags en canvas épais — beige, orange et bleu. Anses longues, impression NAYRO discrète. Parfait pour la plage, le marché ou le quotidien. Résistant et lavable.",
    short_description: "Tote • Canvas • 3 couleurs",
    price: 149,
    compare_at_price: null,
    sku: "NAY-TOTE-TRIO",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "3-1", product_id: "3", url: img("tote1"), alt: "Tote bags trio", position: 0 },
      { id: "3-2", product_id: "3", url: img("tote2"), alt: "Tote détail", position: 1 },
    ],
    variants: [
      { id: "3-beige", product_id: "3", size: "One Size", color_hex: "#0a0a0a", color: "Beige", sku: "NAY-TOTE-BEIGE", stock: 30, price_override: null, is_active: true },
      { id: "3-orange", product_id: "3", size: "One Size", color_hex: "#0a0a0a", color: "Orange", sku: "NAY-TOTE-ORANGE", stock: 20, price_override: null, is_active: true },
      { id: "3-bleu", product_id: "3", size: "One Size", color_hex: "#0a0a0a", color: "Bleu", sku: "NAY-TOTE-BLEU", stock: 22, price_override: null, is_active: true },
    ],
  },
  {
    id: "4",
    slug: "sac-bandouliere-cuir-marron",
    name: "Sac Bandoulière Cuir Marron",
    description: "Sac bandoulière en cuir grainé marron, bandoulière chaîne dorée, fermeture magnétique, intérieur poche zippée. Porté épaule ou croisé. Élégance intemporelle.",
    short_description: "Cuir • Marron • Chaîne",
    price: 249,
    compare_at_price: 299,
    sku: "NAY-BANDOULIERE-MARRON",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "4-1", product_id: "4", url: img("bandouliere1"), alt: "Sac bandoulière marron", position: 0 },
      { id: "4-2", product_id: "4", url: img("bandouliere2"), alt: "Sac bandoulière porté", position: 1 },
    ],
    variants: [
      { id: "4-one", product_id: "4", size: "One Size", color_hex: "#0a0a0a", color: "Marron", sku: "NAY-BANDOULIERE-MARRON-OS", stock: 12, price_override: null, is_active: true },
    ],
  },
  {
    id: "5",
    slug: "sac-cabas-noir-classique",
    name: "Sac Cabas Noir Classique",
    description: "Sac cabas noir intemporel, anses longues, grand volume, poche intérieure zippée. Doublure NAYRO, matière résistante à l'eau. Votre allié quotidien.",
    short_description: "Cabas • Noir • Grand volume",
    price: 189,
    compare_at_price: null,
    sku: "NAY-CABAS-NOIR",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "5-1", product_id: "5", url: img("cabas1"), alt: "Sac cabas noir", position: 0 },
      { id: "5-2", product_id: "5", url: img("cabas2"), alt: "Sac cabas porté", position: 1 },
    ],
    variants: [
      { id: "5-one", product_id: "5", size: "One Size", color_hex: "#0a0a0a", color: "Noir", sku: "NAY-CABAS-NOIR-OS", stock: 20, price_override: null, is_active: true },
    ],
  },
  {
    id: "6",
    slug: "sac-a-dos-rose-pastel",
    name: "Sac à dos Rose Pastel",
    description: "Sac à dos rose poudré, Collection Pastel NAYRO. Matière douce, compartiments multiples, dos respirant. Douceur et praticité pour tous les jours.",
    short_description: "Pastel • Rose • Léger",
    price: 179,
    compare_at_price: null,
    sku: "NAY-SAC-ROSE",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "6-1", product_id: "6", url: img("rose1"), alt: "Sac rose pastel", position: 0 },
      { id: "6-2", product_id: "6", url: img("rose2"), alt: "Sac rose collection", position: 1 },
    ],
    variants: [
      { id: "6-one", product_id: "6", size: "One Size", color_hex: "#0a0a0a", color: "Rose", sku: "NAY-SAC-ROSE-OS", stock: 15, price_override: null, is_active: true },
    ],
  },
  {
    id: "7",
    slug: "sac-a-dos-scolaire-noir",
    name: "Sac à dos Scolaire Noir",
    description: "Sac à dos scolaire noir, renforcé, grande capacité, poche ordinateur, bretelles ergonomiques. Pour étudiants et professionnels. NAYRO qualité.",
    short_description: "Scolaire • Noir • Renforcé",
    price: 189,
    compare_at_price: null,
    sku: "NAY-SAC-SCOLAIRE-NOIR",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "7-1", product_id: "7", url: img("scolaire1"), alt: "Sac scolaire noir", position: 0 },
      { id: "7-2", product_id: "7", url: img("scolaire2"), alt: "Sac scolaire dos", position: 1 },
    ],
    variants: [
      { id: "7-one", product_id: "7", size: "One Size", color_hex: "#0a0a0a", color: "Noir", sku: "NAY-SAC-SCOLAIRE-NOIR-OS", stock: 22, price_override: null, is_active: true },
    ],
  },
  {
    id: "8",
    slug: "pochette-nayro-minimal",
    name: "Pochette NAYRO Minimal",
    description: "Pochette minimaliste NAYRO, fermeture zippée, dragonne, intérieur compartimenté. Parfaite pour soirées ou en complément d'un sac.",
    short_description: "Pochette • Minimal",
    price: 99,
    compare_at_price: null,
    sku: "NAY-POCHETTE",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "accessories",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "8-1", product_id: "8", url: img("pochette1"), alt: "Pochette NAYRO", position: 0 },
      { id: "8-2", product_id: "8", url: img("pochette2"), alt: "Pochette intérieur", position: 1 },
    ],
    variants: [
      { id: "8-one", product_id: "8", size: "One Size", color_hex: "#0a0a0a", color: "Noir", sku: "NAY-POCHETTE-NOIR-OS", stock: 30, price_override: null, is_active: true },
    ],
  },
  {
    id: "9",
    slug: "sac-de-plage-nayro",
    name: "Sac de Plage NAYRO",
    description: "Sac de plage XXL, toile résistante, anses longues, poche imperméable. Inspiré du coucher de soleil de la côte marocaine. Votre compagnon d'été.",
    short_description: "Plage • XXL • Imperméable",
    price: 129,
    compare_at_price: null,
    sku: "NAY-PLAGE",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "9-1", product_id: "9", url: img("plage1"), alt: "Sac plage", position: 0 },
      { id: "9-2", product_id: "9", url: img("plage2"), alt: "Sac plage détail", position: 1 },
    ],
    variants: [
      { id: "9-one", product_id: "9", size: "One Size", color_hex: "#0a0a0a", color: "Beige", sku: "NAY-PLAGE-BEIGE-OS", stock: 18, price_override: null, is_active: true },
    ],
  },
  {
    id: "10",
    slug: "montre-verte-nayro",
    name: "Montre Verte NAYRO",
    description: "Montre verte cadran 40mm, bracelet silicone, étanche 50M, mouvement précis. L'accessoire qui complète votre look NAYRO. Édition limitée.",
    short_description: "Montre • Verte • 40mm",
    price: 299,
    compare_at_price: 399,
    sku: "NAY-MONTRE-VERTE",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "accessories",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "10-1", product_id: "10", url: img("montre1"), alt: "Montre verte", position: 0 },
      { id: "10-2", product_id: "10", url: img("montre2"), alt: "Montre détail", position: 1 },
    ],
    variants: [
      { id: "10-one", product_id: "10", size: "One Size", color_hex: "#0a0a0a", color: "Vert", sku: "NAY-MONTRE-VERTE-OS", stock: 10, price_override: null, is_active: true },
    ],
  },
  {
    id: "11",
    slug: "sac-fourre-tout-lacoste-style",
    name: "Sac Fourre-Tout Lacoste Style",
    description: "Sac fourre-tout style Lacoste, toile épaisse, logo brodé, anses contrastées. Pour un look casual chic. Collection été NAYRO.",
    short_description: "Fourre-tout • Style Lacoste",
    price: 159,
    compare_at_price: null,
    sku: "NAY-FOURRE-TOUT",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "11-1", product_id: "11", url: img("fourre1"), alt: "Sac fourre-tout", position: 0 },
      { id: "11-2", product_id: "11", url: img("fourre2"), alt: "Sac fourre-tout détail", position: 1 },
    ],
    variants: [
      { id: "11-one", product_id: "11", size: "One Size", color_hex: "#0a0a0a", color: "Blanc/Bleu", sku: "NAY-FOURRE-TOUT-OS", stock: 16, price_override: null, is_active: true },
    ],
  },
  {
    id: "12",
    slug: "ensemble-nayro-vert-bleu",
    name: "Ensemble NAYRO Vert/Bleu",
    description: "Ensemble coordonné: sac à dos bleu + pochette verte. Pour un look NAYRO complet. Remise pack inclus. Idéal cadeau.",
    short_description: "Pack • Sac + Pochette",
    price: 349,
    compare_at_price: 399,
    sku: "NAY-ENSEMBLE",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "sacs",
    audience: "unisex",
    collection_id: null,
    primary_color: "#0a0a0a",
    primary_color_name: "Noir",
    is_active: true,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-08-31T00:00:00Z",
    updated_at: "2026-08-31T00:00:00Z",
    images: [
      { id: "12-1", product_id: "12", url: img("ensemble1"), alt: "Ensemble NAYRO", position: 0 },
      { id: "12-2", product_id: "12", url: img("ensemble2"), alt: "Ensemble détail", position: 1 },
    ],
    variants: [
      { id: "12-one", product_id: "12", size: "One Size", color_hex: "#0a0a0a", color: "Vert/Bleu", sku: "NAY-ENSEMBLE-OS", stock: 8, price_override: null, is_active: true },
    ],
  },
]
