import type { Product, Category } from "./types"

export const mockCategories: Category[] = [
  { id: "1", slug: "women", name: "Women", description: "Womenswear", image_url: null, position: 1 },
  { id: "2", slug: "men", name: "Men", description: "Menswear", image_url: null, position: 2 },
  { id: "3", slug: "shoes", name: "Shoes", description: "Footwear", image_url: null, position: 3 },
  { id: "4", slug: "accessories", name: "Accessories", description: "Accessories", image_url: null, position: 4 },
]

const img = (id: number, w = 800, h = 1000) => `https://picsum.photos/seed/nayro${id}/${w}/${h}`

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "robe-chemise-linen-belted",
    name: "Robe Chemise Linen Belted",
    description: "Robe chemise en lin mélangé, coupe fluide et ceinture à nouer. Finitions soignées, fente discrète et boutons en corozo. Une pièce versatile pour le quotidien et les soirées d'été.",
    short_description: "Robe chemise lin • Ceinture incluse",
    price: 649,
    compare_at_price: null,
    sku: "NAY-W-001",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "women",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-01-15T00:00:00Z",
    images: [
      { id: "1-1", product_id: "1", url: img(11), alt: "Robe chemise linen", position: 0 },
      { id: "1-2", product_id: "1", url: img(12), alt: "Robe chemise back", position: 1 },
    ],
    variants: [
      { id: "1-xs", product_id: "1", size: "XS", color: "Ivory", sku: "NAY-W-001-XS", stock: 5, price_override: null },
      { id: "1-s", product_id: "1", size: "S", color: "Ivory", sku: "NAY-W-001-S", stock: 8, price_override: null },
      { id: "1-m", product_id: "1", size: "M", color: "Ivory", sku: "NAY-W-001-M", stock: 3, price_override: null },
      { id: "1-l", product_id: "1", size: "L", color: "Ivory", sku: "NAY-W-001-L", stock: 2, price_override: null },
    ],
  },
  {
    id: "2",
    slug: "blazer-structured-wool",
    name: "Blazer Structured Wool",
    description: "Blazer structuré en laine froide, épaule douce et coupe droite. Doublure viscose, poches passepoilées et boutons recouverts. L'essence du vestiaire NAYRO.",
    short_description: "Blazer laine froide • Coupe droite",
    price: 899,
    compare_at_price: 1199,
    sku: "NAY-W-002",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "women",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-01-10T00:00:00Z",
    images: [
      { id: "2-1", product_id: "2", url: img(21), alt: "Blazer wool", position: 0 },
      { id: "2-2", product_id: "2", url: img(22), alt: "Blazer detail", position: 1 },
    ],
    variants: [
      { id: "2-s", product_id: "2", size: "S", color: "Black", sku: "NAY-W-002-S", stock: 4, price_override: null },
      { id: "2-m", product_id: "2", size: "M", color: "Black", sku: "NAY-W-002-M", stock: 6, price_override: null },
      { id: "2-l", product_id: "2", size: "L", color: "Black", sku: "NAY-W-002-L", stock: 2, price_override: null },
    ],
  },
  {
    id: "3",
    slug: "trousers-wide-leg-wool",
    name: "Trousers Wide Leg Wool",
    description: "Pantalon large taille haute, jambe fluide et pli creux. Laine mélangée et finitions main. Parfait avec le blazer assorti.",
    short_description: "Pantalon large • Laine mélangée",
    price: 549,
    compare_at_price: null,
    sku: "NAY-W-003",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "women",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
    images: [
      { id: "3-1", product_id: "3", url: img(31), alt: "Trousers wide leg", position: 0 },
      { id: "3-2", product_id: "3", url: img(32), alt: "Trousers back", position: 1 },
    ],
    variants: [
      { id: "3-xs", product_id: "3", size: "XS", color: "Charcoal", sku: "NAY-W-003-XS", stock: 7, price_override: null },
      { id: "3-s", product_id: "3", size: "S", color: "Charcoal", sku: "NAY-W-003-S", stock: 10, price_override: null },
      { id: "3-m", product_id: "3", size: "M", color: "Charcoal", sku: "NAY-W-003-M", stock: 5, price_override: null },
    ],
  },
  {
    id: "4",
    slug: "chemise-overshirt-cotton",
    name: "Overshirt Cotton Canvas",
    description: "Surchemise en canvas de coton lourd, coupe boxy et poches plaquées. Patte boutonnée, surpiqûres contrastées et lavage garment-dyed.",
    short_description: "Surchemise canvas • Coton lourd",
    price: 599,
    compare_at_price: null,
    sku: "NAY-M-001",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "men",
    collection_id: null,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-02-05T00:00:00Z",
    images: [
      { id: "4-1", product_id: "4", url: img(41), alt: "Overshirt", position: 0 },
      { id: "4-2", product_id: "4", url: img(42), alt: "Overshirt detail", position: 1 },
    ],
    variants: [
      { id: "4-m", product_id: "4", size: "M", color: "Stone", sku: "NAY-M-001-M", stock: 8, price_override: null },
      { id: "4-l", product_id: "4", size: "L", color: "Stone", sku: "NAY-M-001-L", stock: 5, price_override: null },
      { id: "4-xl", product_id: "4", size: "XL", color: "Stone", sku: "NAY-M-001-XL", stock: 3, price_override: null },
    ],
  },
  {
    id: "5",
    slug: "knit-merino-crew",
    name: "Knit Merino Crew",
    description: "Pull ras-du-cou en mérinos extra-fin, maille fine jauge 14. Encolure côtelée et finitions bord-côte. Léger, chaud et respirant.",
    short_description: "Pull mérinos • Maille fine",
    price: 479,
    compare_at_price: null,
    sku: "NAY-M-002",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "men",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-01-20T00:00:00Z",
    images: [
      { id: "5-1", product_id: "5", url: img(51), alt: "Knit merino", position: 0 },
      { id: "5-2", product_id: "5", url: img(52), alt: "Knit detail", position: 1 },
    ],
    variants: [
      { id: "5-s", product_id: "5", size: "S", color: "Camel", sku: "NAY-M-002-S", stock: 6, price_override: null },
      { id: "5-m", product_id: "5", size: "M", color: "Camel", sku: "NAY-M-002-M", stock: 9, price_override: null },
      { id: "5-l", product_id: "5", size: "L", color: "Camel", sku: "NAY-M-002-L", stock: 4, price_override: null },
    ],
  },
  {
    id: "6",
    slug: "coat-long-wool-blend",
    name: "Coat Long Wool Blend",
    description: "Manteau long en drap de laine mélangée, col tailleur et ceinture détachable. Ligne épurée, fente au dos et poches intérieures.",
    short_description: "Manteau long • Drap laine",
    price: 1299,
    compare_at_price: null,
    sku: "NAY-M-003",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "men",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
    images: [
      { id: "6-1", product_id: "6", url: img(61), alt: "Coat long", position: 0 },
      { id: "6-2", product_id: "6", url: img(62), alt: "Coat detail", position: 1 },
    ],
    variants: [
      { id: "6-m", product_id: "6", size: "M", color: "Black", sku: "NAY-M-003-M", stock: 3, price_override: null },
      { id: "6-l", product_id: "6", size: "L", color: "Black", sku: "NAY-M-003-L", stock: 2, price_override: null },
    ],
  },
  {
    id: "7",
    slug: "loafer-leather-penny",
    name: "Loafer Leather Penny",
    description: "Mocassin penny en cuir de veau lisse, cousu Blake et semelle cuir. Patine naturelle et confort immédiat.",
    short_description: "Mocassin cuir • Cousu Blake",
    price: 749,
    compare_at_price: 949,
    sku: "NAY-S-001",
    brand: "NAYRO",
    category_id: "3",
    category_slug: "shoes",
    collection_id: null,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-01-12T00:00:00Z",
    updated_at: "2026-01-12T00:00:00Z",
    images: [
      { id: "7-1", product_id: "7", url: img(71), alt: "Loafer", position: 0 },
      { id: "7-2", product_id: "7", url: img(72), alt: "Loafer sole", position: 1 },
    ],
    variants: [
      { id: "7-39", product_id: "7", size: "39", color: "Black", sku: "NAY-S-001-39", stock: 4, price_override: null },
      { id: "7-40", product_id: "7", size: "40", color: "Black", sku: "NAY-S-001-40", stock: 6, price_override: null },
      { id: "7-41", product_id: "7", size: "41", color: "Black", sku: "NAY-S-001-41", stock: 5, price_override: null },
      { id: "7-42", product_id: "7", size: "42", color: "Black", sku: "NAY-S-001-42", stock: 3, price_override: null },
    ],
  },
  {
    id: "8",
    slug: "ballet-flat-soft-leather",
    name: "Ballet Flat Soft Leather",
    description: "Ballerine en agneau souple, bout amande et élastique invisible. Semelle fine et confort enveloppant.",
    short_description: "Ballerine agneau • Bout amande",
    price: 529,
    compare_at_price: null,
    sku: "NAY-S-002",
    brand: "NAYRO",
    category_id: "3",
    category_slug: "shoes",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-02-12T00:00:00Z",
    updated_at: "2026-02-12T00:00:00Z",
    images: [
      { id: "8-1", product_id: "8", url: img(81), alt: "Ballet flat", position: 0 },
      { id: "8-2", product_id: "8", url: img(82), alt: "Ballet flat side", position: 1 },
    ],
    variants: [
      { id: "8-37", product_id: "8", size: "37", color: "Beige", sku: "NAY-S-002-37", stock: 5, price_override: null },
      { id: "8-38", product_id: "8", size: "38", color: "Beige", sku: "NAY-S-002-38", stock: 7, price_override: null },
      { id: "8-39", product_id: "8", size: "39", color: "Beige", sku: "NAY-S-002-39", stock: 4, price_override: null },
    ],
  },
  {
    id: "9",
    slug: "bag-leather-tote",
    name: "Bag Leather Tote",
    description: "Cabas en cuir grainé, anses longues et poche intérieure zippée. Doublure canvas et fermeture aimantée.",
    short_description: "Cabas cuir grainé • Anses longues",
    price: 689,
    compare_at_price: null,
    sku: "NAY-A-001",
    brand: "NAYRO",
    category_id: "4",
    category_slug: "accessories",
    collection_id: null,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: false,
    created_at: "2026-01-25T00:00:00Z",
    updated_at: "2026-01-25T00:00:00Z",
    images: [
      { id: "9-1", product_id: "9", url: img(91), alt: "Tote bag", position: 0 },
      { id: "9-2", product_id: "9", url: img(92), alt: "Tote bag interior", position: 1 },
    ],
    variants: [
      { id: "9-one", product_id: "9", size: "One Size", color: "Black", sku: "NAY-A-001-OS", stock: 12, price_override: null },
    ],
  },
  {
    id: "10",
    slug: "scarf-wool-cashmere",
    name: "Scarf Wool Cashmere",
    description: "Écharpe en laine et cachemire, tissage sergé et franges roulottées main. Douceur et chaleur incomparables.",
    short_description: "Écharpe laine-cachemire • Franges main",
    price: 329,
    compare_at_price: null,
    sku: "NAY-A-002",
    brand: "NAYRO",
    category_id: "4",
    category_slug: "accessories",
    collection_id: null,
    is_active: true,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    created_at: "2026-01-18T00:00:00Z",
    updated_at: "2026-01-18T00:00:00Z",
    images: [
      { id: "10-1", product_id: "10", url: img(101), alt: "Scarf", position: 0 },
      { id: "10-2", product_id: "10", url: img(102), alt: "Scarf texture", position: 1 },
    ],
    variants: [
      { id: "10-one", product_id: "10", size: "One Size", color: "Camel", sku: "NAY-A-002-OS", stock: 15, price_override: null },
    ],
  },
  {
    id: "11",
    slug: "dress-slip-satin",
    name: "Dress Slip Satin",
    description: "Robe nuisette en satin de viscose, bretelles fines réglables et biais contrasté. Coupe fluide et tombé irréprochable.",
    short_description: "Robe satin • Bretelles fines",
    price: 579,
    compare_at_price: 749,
    sku: "NAY-W-004",
    brand: "NAYRO",
    category_id: "1",
    category_slug: "women",
    collection_id: null,
    is_active: true,
    is_featured: false,
    is_new: false,
    is_bestseller: false,
    created_at: "2026-01-08T00:00:00Z",
    updated_at: "2026-01-08T00:00:00Z",
    images: [
      { id: "11-1", product_id: "11", url: img(111), alt: "Slip dress", position: 0 },
      { id: "11-2", product_id: "11", url: img(112), alt: "Slip dress back", position: 1 },
    ],
    variants: [
      { id: "11-xs", product_id: "11", size: "XS", color: "Black", sku: "NAY-W-004-XS", stock: 4, price_override: null },
      { id: "11-s", product_id: "11", size: "S", color: "Black", sku: "NAY-W-004-S", stock: 6, price_override: null },
      { id: "11-m", product_id: "11", size: "M", color: "Black", sku: "NAY-W-004-M", stock: 3, price_override: null },
    ],
  },
  {
    id: "12",
    slug: "shirt-poplin-oversized",
    name: "Shirt Poplin Oversized",
    description: "Chemise oversize en popeline de coton biologique, col français et poignets mousquetaires. Coupe généreuse et plis d'aisance au dos.",
    short_description: "Chemise popeline • Coton bio",
    price: 429,
    compare_at_price: null,
    sku: "NAY-M-004",
    brand: "NAYRO",
    category_id: "2",
    category_slug: "men",
    collection_id: null,
    is_active: true,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    created_at: "2026-02-08T00:00:00Z",
    updated_at: "2026-02-08T00:00:00Z",
    images: [
      { id: "12-1", product_id: "12", url: img(121), alt: "Poplin shirt", position: 0 },
      { id: "12-2", product_id: "12", url: img(122), alt: "Poplin shirt detail", position: 1 },
    ],
    variants: [
      { id: "12-m", product_id: "12", size: "M", color: "White", sku: "NAY-M-004-M", stock: 10, price_override: null },
      { id: "12-l", product_id: "12", size: "L", color: "White", sku: "NAY-M-004-L", stock: 8, price_override: null },
      { id: "12-xl", product_id: "12", size: "XL", color: "White", sku: "NAY-M-004-XL", stock: 5, price_override: null },
    ],
  },
]
